package com.mobdeve.s15.animall

object CityDataHelper {
    fun initializeCityData(): Array<String> {
        return arrayOf(
            "Caloocan, Metro Manila",
            "Las Pinas, Metro Manila",
            "Makati, Metro Manila",
            "Malabon, Metro Manila",
            "Mandaluyong, Metro Manila",
            "Manila, Metro Manila",
            "Marikina, Metro Manila",
            "Muntinlupa, Metro Manila",
            "Navotas, Metro Manila",
            "Paranaque, Metro Manila",
            "Pasay, Metro Manila",
            "Pasig, Metro Manila",
            "Quezon City, Metro Manila",
            "San Juan, Metro Manila",
            "Taguig, Metro Manila",
            "Valenzuela, Metro Manila",
            "Butuan, Agusan del Norte",
            "Cabadbaran, Agusan del Norte",
            "Bayugan, Agusan del Sur",
            "Legazpi, Albay",
            "Ligao, Albay",
            "Tabaco, Albay",
            "Isabela, Basilan",
            "Lamitan, Basilan",
            "Balanga, Bataan",
            "Batangas City, Batangas",
            "Lipa, Batangas",
            "Tanauan, Batangas",
            "Baguio, Benguet",
            "Tagbilaran, Bohol",
            "Malaybalay, Bukidnon",
            "Valencia, Bukidnon",
            "Malolos, Bulacan",
            "Meycauayan, Bulacan",
            "San Jose del Monte, Bulacan",
            "Tuguegarao, Cagayan",
            "Iriga, Camarines Sur",
            "Naga, Camarines Sur",
            "Roxas, Capiz",
            "Bacoor, Cavite",
            "Cavite City, Cavite",
            "Dasmarinas, Cavite",
            "Imus, Cavite",
            "Tagaytay, Cavite",
            "Trece Martires, Cavite",
            "Bogo, Cebu",
            "Carcar, Cebu",
            "Cebu City, Cebu",
            "Danao, Cebu",
            "Lapu-Lapu, Cebu",
            "Mandaue, Cebu",
            "Naga, Cebu",
            "Talisay, Cebu",
            "Toledo, Cebu",
            "Kidapawan, Cotabato (North)",
            "Panabo, Davao del Norte",
            "Samal, Davao del Norte",
            "Tagum, Davao del Norte",
            "Davao City, Davao del Sur",
            "Digos, Davao del Sur",
            "Mati, Davao Oriental",
            "Borongan, Eastern Samar",
            "Batac, Ilocos Norte",
            "Laoag, Ilocos Norte",
            "Candon, Ilocos Sur",
            "Vigan, Ilocos Sur",
            "Iloilo City, Iloilo",
            "Passi, Iloilo",
            "Cauayan, Isabela",
            "Ilagan, Isabela",
            "Santiago, Isabela",
            "Tabuk, Kalinga",
            "San Fernando, La Union",
            "Binan, Laguna",
            "Cabuyao, Laguna",
            "Calamba, Laguna",
            "San Pablo, Laguna",
            "Santa Rosa, Laguna",
            "San Pedro, Laguna",
            "Iligan, Lanao del Norte",
            "Marawi, Lanao del Sur",
            "Baybay, Leyte",
            "Ormoc, Leyte",
            "Tacloban, Leyte",
            "Cotabato City, Maguindanao",
            "Masbate City, Masbate",
            "Oroquieta, Misamis Occidental",
            "Ozamiz, Misamis Occidental",
            "Tangub, Misamis Occidental",
            "Cagayan de Oro, Misamis Oriental",
            "El Salvador, Misamis Oriental",
            "Gingoog, Misamis Oriental",
            "Bacolod, Negros Occidental",
            "Bago, Negros Occidental",
            "Cadiz, Negros Occidental",
            "Escalante, Negros Occidental",
            "Himamaylan, Negros Occidental",
            "Kabankalan, Negros Occidental",
            "La Carlota, Negros Occidental",
            "Sagay, Negros Occidental",
            "San Carlos, Negros Occidental",
            "Silay, Negros Occidental",
            "Sipalay, Negros Occidental",
            "Talisay, Negros Occidental",
            "Victorias, Negros Occidental",
            "Bais, Negros Oriental",
            "Bayawan, Negros Oriental",
            "Canlaon, Negros Oriental",
            "Dumaguete, Negros Oriental",
            "Guihulngan, Negros Oriental",
            "Tanjay, Negros Oriental",
            "Cabanatuan, Nueva Ecija",
            "Gapan, Nueva Ecija",
            "Munoz, Nueva Ecija",
            "Palayan, Nueva Ecija",
            "San Jose, Nueva Ecija",
            "Calapan, Oriental Mindoro",
            "Puerto Princesa, Palawan",
            "Angeles, Pampanga",
            "Mabalacat, Pampanga",
            "San Fernando, Pampanga",
            "Alaminos, Pangasinan",
            "Dagupan, Pangasinan",
            "San Carlos, Pangasinan",
            "Urdaneta, Pangasinan",
            "Lucena, Quezon",
            "Tayabas, Quezon",
            "Antipolo, Rizal",
            "Calbayog, Samar (Western)",
            "Catbalogan, Samar (Western)",
            "Sorsogon City, Sorsogon",
            "General Santos, South Cotabato",
            "Koronadal, South Cotabato",
            "Maasin, Southern Leyte",
            "Tacurong, Sultan Kudarat",
            "Surigao City, Surigao del Norte",
            "Bislig, Surigao del Sur",
            "Tandag, Surigao del Sur",
            "Tarlac City, Tarlac",
            "Olongapo, Zambales",
            "Dapitan, Zamboanga del Norte",
            "Dipolog, Zamboanga del Norte",
            "Pagadian, Zamboanga del Sur",
            "Zamboanga City, Zamboanga del Sur"
        )
    }
}